### ISSUE TITLE
Front-end and Back-End for Login

### ISSUE THREAD

**Issue by ShumolliArber** [ShumolliArber/Evento#2]

**Comment by arimeha** [comment]
[evento slices.zip](https://github.com/ShumolliArber/Evento/files/2999654/evento.slices.zip)
files needed

**Comment by arimeha** [comment]
[evento slices.zip](https://github.com/ShumolliArber/Evento/files/3040902/evento.slices.zip)
Files with fixes

**Comment by arimeha** [comment]
![Untitled-1](https://user-images.githubusercontent.com/48391867/56246012-23e93d00-60a1-11e9-92a6-7555a0ac3ba8.png)
Background+Gradient
